services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    env_file:
      - .env

  ui:
    build:
      context: .
      dockerfile: Dockerfile.ui
    ports:
      - "3001:3001"
    environment:
      - NODE_ENV=production
      - PORT=3001

  nginx:
    image: nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - backend
      - ui
