# Usa Node como imagen base
FROM node:18

# Carpeta de trabajo
WORKDIR /app

# Copia solo package.json y package-lock.json
COPY UI/package*.json ./

# Instalamos dependencias
RUN npm install

# Copiamos el resto del código
COPY UI .

# Aquí haces el build de producción (compilar Svelte)
RUN npm run build

# Expone el puerto 3001
EXPOSE 3001

# Ahora sirves el directorio de producción
CMD ["npx", "sirv", "public", "--no-clear", "--single", "--host", "0.0.0.0", "--port", "3001"]
